# Default values for chart.

replicaCount: 1

plugins: farski-blendstat-panel,grafana-simple-json-datasource,https://github.com/sunny0826/aliyun-cms-grafana/archive/master.zip;aliyun-cms-grafana

access_key_id: ""
access_secret: ""
region_id: "cn-shanghai"
password: "admin"

image:
  repository: grafana/grafana
  pullPolicy: IfNotPresent

build_image:
  repository: guoxudongdocker/grafana-build
  tag: 0.2.1-release
  pullPolicy: Always

backend_image:
  repository: guoxudongdocker/grafana-build
  tag: 0.2.1-release
  pullPolicy: Always

cronjob_image:
  repository: odise/busybox-curl
  tag: latest

schedule: "30 2 * * *"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: grafana.chart-example.local
      paths: ['/']

  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

backend_resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

affinity: {}
