---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kk-grafana-cms.fullname" . }}-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kk-grafana-cms.fullname" . }}-cr
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kk-grafana-cms.fullname" . }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kk-grafana-cms.fullname" . }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ template "kk-grafana-cms.fullname" . }}-sa
    namespace: {{.Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kk-grafana-cms.fullname" . }}-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kk-grafana-cms.fullname" . }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ template "kk-grafana-cms.fullname" . }}-sa
    namespace: {{.Release.Namespace }}