apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "cms-cronjob"
  labels:
{{ include "kk-grafana-cms.labels" . | indent 4 }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cronejob
            image: {{ .Values.cronjob_image.repository }}:{{ .Values.cronjob_image.tag }}
            command:
              - "/bin/sh"
              - "-c"
              - "curl"
              - {{ template "cms-variable.fullname" . }}/refresh