apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "cms-cronjob"
  labels:
{{ include "kk-grafana-cms.labels" . | indent 4 }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Chart.Name }}-sa
          imagePullSecrets:
          - name: registry-pull-secret
          restartPolicy: OnFailure
          containers:
          - name: cronejob
            image: "odise/busybox-curl"
            command:
              - "/bin/sh"
              - "-c"
              - "curl"
              - {{ template "cms-variable.fullname" . }}/refresh