apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cms-secret.fullname" . }}
  labels:
{{ include "kk-grafana-cms.labels" . | indent 4 }}
type: Opaque
data:
  accessKeyId: {{ .Values.access_key_id | b64enc }}
  accessSecret: {{ .Values.access_secret | b64enc}}
  adminPass: {{ .Values.password | b64enc}}

stringData:
  datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
     - name: CMS Grafana Service
       orgId: 1
    datasources:
     - name: CMS Grafana Service
       type: aliyun_cms_grafana_datasource
       access: proxy
       url: http://metrics.{{ .Values.region_id }}.aliyuncs.com
       basicAuth: false
       withCredentials: false
       isDefault: true
       jsonData:
         cmsAccessKey: {{ .Values.access_key_id | b64enc }}
         cmsSecretKey: {{ .Values.access_secret | b64enc }}
         keepCookies: []
       secureJsonFields: {}
       readOnly: false

     - name: Variable DataSource
       type: grafana-simple-json-datasource
       access: proxy
       url: http://{{ template "cms-variable.fullname" . }}
       basicAuth: false
       withCredentials: false
       isDefault: false
       jsonData:
         keepCookies: []
       secureJsonFields: {}
       readOnly: false